apiVersion: v1
kind: Service
metadata:
  name: {{.serviceName}}
spec:
  selector:
    app: {{.app}}
    tier: {{.tier}}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.app}}
    tier: {{.tier}}
  name: {{.deployName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mm-rest
      tier: backend
  template:
    metadata:
      labels:
        app: mm-rest
        tier: backend
    spec:
      containers:
      - image: {{.image}}
        name: mm-rest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: CLUSTER_ENV
          value: "dev"
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 25%
    type: RollingUpdate
